package test

import "testing"
import s "serpent_aes/serpent"

func TestLongStringEncryption(test *testing.T) {
	var serpent s.Serpent
	var strongUserKey string = "c34*E@ywiqsdPaN!U2W3"
	var longMessage string = "this is a long long text with @@@timefakfagmo/()"
	var targetEncryptedMessage string = "TVRFd01UQXdNREV4TVRFeE1EQXdNVEV3TURFeE1UQXhNREV4TURBd01EQXdNREV4TURFd01UQXhNVEV4TVRBeE1EQXhNVEV3TVRBeE1UQXdNREV3TURFd01UQXhNVEV3TURBd01ERXhNVEF4TURFd01UQXhNREF4TVRFeE1UQXdNVEF3TURBd01UQXhNREF3TURFeE1URXdNVEV3TVRBd01URXhNREF4TVRFPQ==TURFd01ERXdNREV3TVRFd01ERXdNREF4TURFd01EQXdNVEF4TVRBeE1ERXhNREV4TVRBeE1ERXdNVEV4TVRBeE1URXdNREF3TVRFd01ERXhNVEV4TURBeE1UQXdNREF4TVRFd01ERXdNVEV4TURBeE1EQXhNREF3TVRFeE1URXdNREF3TVRBeE1ERXdNVEV3TVRFd01UQXdNREF4TURBeE1EQXhNREV4TURBPQ==TURFd01URXhNVEF3TURFd01URXdNVEF3TVRFd01URXhNREF4TURFd01ERXhNVEF4TVRFd01UQXhNVEV3TVRBd01UQXdNREF3TVRBeE1EQXhNREV4TVRFd01EQXdNVEF4TVRBeE1UQXdNREV3TURFd01URXdNVEV4TURBeE1UQXdNREV4TURFeE1EQXdNREV3TVRFeE1EQXhNVEF3TVRBd01URXhNVEV3TVRBPQ=="

	var encryptedMessage string = serpent.EncryptText(longMessage, strongUserKey)

	if targetEncryptedMessage != encryptedMessage {
		test.Errorf("Encrypted messages doesn't match (%s) != (%s)", targetEncryptedMessage, encryptedMessage)
		test.Fail()
	}
}

func TestLongStringDecryption(test *testing.T) {
	var serpent s.Serpent
	var strongUserKey string = "c34*E@ywiqsdPaN!U2W3"
	var encryptedMessage string = "TVRFd01UQXdNREV4TVRFeE1EQXdNVEV3TURFeE1UQXhNREV4TURBd01EQXdNREV4TURFd01UQXhNVEV4TVRBeE1EQXhNVEV3TVRBeE1UQXdNREV3TURFd01UQXhNVEV3TURBd01ERXhNVEF4TURFd01UQXhNREF4TVRFeE1UQXdNVEF3TURBd01UQXhNREF3TURFeE1URXdNVEV3TVRBd01URXhNREF4TVRFPQ==TURFd01ERXdNREV3TVRFd01ERXdNREF4TURFd01EQXdNVEF4TVRBeE1ERXhNREV4TVRBeE1ERXdNVEV4TVRBeE1URXdNREF3TVRFd01ERXhNVEV4TURBeE1UQXdNREF4TVRFd01ERXdNVEV4TURBeE1EQXhNREF3TVRFeE1URXdNREF3TVRBeE1ERXdNVEV3TVRFd01UQXdNREF4TURBeE1EQXhNREV4TURBPQ==TURFd01URXhNVEF3TURFd01URXdNVEF3TVRFd01URXhNREF4TURFd01ERXhNVEF4TVRFd01UQXhNVEV3TVRBd01UQXdNREF3TVRBeE1EQXhNREV4TVRFd01EQXdNVEF4TVRBeE1UQXdNREV3TURFd01URXdNVEV4TURBeE1UQXdNREV4TURFeE1EQXdNREV3TVRFeE1EQXhNVEF3TVRBd01URXhNVEV3TVRBPQ=="
	var targetDecryptedMessage string = "this is a long long text with @@@timefakfagmo/()"

	var decryptedMessage string = serpent.DecryptText(encryptedMessage, strongUserKey)

	if targetDecryptedMessage != decryptedMessage {
		test.Errorf("Decrypted messages doesn't match (%s) != (%s)", targetDecryptedMessage, decryptedMessage)
		test.Fail()
	}
}
