
// Objective-C API for talking to the following Go packages
//
//	serpent_aes
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Serpent_aes_FRAMEWORK_H__
#define __Serpent_aes_FRAMEWORK_H__

#include "Serpent_aes.objc.h"
#include "Universe.objc.h"

#endif
