// Objective-C API for talking to serpent_aes Go package.
//   gobind -lang=objc serpent_aes
//
// File is generated by gobind. Do not edit.

#ifndef __Serpent_aes_H__
#define __Serpent_aes_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull Serpent_aesSerpentDecrypt(NSString* _Nullable encryptedText, NSString* _Nullable key);

FOUNDATION_EXPORT NSString* _Nonnull Serpent_aesSerpentEncrypt(NSString* _Nullable plainText, NSString* _Nullable key);

#endif
